VS_Project/FullViajes/FullViajes/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Web.Http;
using System.Web.Http.Description;
using FullViajes.Models;

namespace FullViajes.Controllers
{
    public class UsersController : ApiController
    {
        private FullViajesEntities db = new FullViajesEntities();

        public string MessaError { get; private set; }

        // GET: api/Users
        public IQueryable<Usuario> GetUsuario()
        {
            return db.Usuario;
        }

        // GET: api/Users/5
        [ResponseType(typeof(Usuario))]
        public IHttpActionResult GetUsuario(long id)
        {
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return NotFound();
            }

            return Ok(usuario);
        }

        // PUT: api/Users/5
        [Route("api/Users/editar")]
        [ResponseType(typeof(void))]
        public IHttpActionResult Editar(long id, Usuario usuario)
        {
            string MensajeError = "Error";
            Usuario user = db.Usuario.Where(a => a.id_usuario == id).FirstOrDefault();
            if (user != null)
            {
               /*
                //CHEQUEA QUE EL MAIL NO ESTA EN USO
                Usuario emailcheck = db.Usuario.Where(a => a.email == usuario.email).FirstOrDefault();
                if (emailcheck != null)
                {
                    MensajeError = "El email " + usuario.email + " ya se encuentra registrado";
                    return BadRequest(MensajeError);
                }
                //CHEQUEA QUE EL NOMBRE DE USUARIO NO ESTE EN USO
                Usuario usercheck = db.Usuario.Where(a => a.nickname == usuario.nickname).FirstOrDefault();
                if (usercheck != null)
                {
                    MensajeError = "El usuario " + usuario.nickname + " ya se encuentra registrado";
                    return BadRequest(MensajeError);
                }
                */
                user.nickname = usuario.nickname;
                user.nombre = usuario.nombre;
                user.apellido = usuario.apellido;
                user.email = usuario.email;
                user.rol = usuario.rol;
                user.user_descripcion = usuario.user_descripcion;
                db.Entry(user).State = EntityState.Modified;

            }
               /* if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != usuario.id_usuario)
            {
                return BadRequest();
            }

            db.Entry(usuario).State = EntityState.Modified;
            */
            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UsuarioExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

 [HttpGet]
        [Route("api/Users/act")]
        [ResponseType(typeof(void))]
        public IHttpActionResult Act(long id)
        {
            Usuario user = db.Usuario.Where(a => a.id_usuario == id).FirstOrDefault();
            if (user != null)
            {
                user.active = true;
                db.Entry(user).State = EntityState.Modified;

            }
            try
            {
                db.SaveChanges();
                return NotFound();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UsuarioExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        [HttpGet]
        [Route("api/Users/dst")]
        [ResponseType(typeof(void))]
        public IHttpActionResult Dst(long id)
        {
            Usuario user = db.Usuario.Where(a => a.id_usuario == id).FirstOrDefault();
            if (user != null)
            {
                user.active = false;
                db.Entry(user).State = EntityState.Modified;

            }
            try
            {
                db.SaveChanges();
                return NotFound();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UsuarioExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        [HttpGet]
        [Route("api/Users/Verifica")]
        [ResponseType(typeof(void))]
        public IHttpActionResult Verifica(string tkn)
        {
            Usuario user = db.Usuario.Where(a => a.token == tkn).FirstOrDefault();
            if (user != null)
            {
                user.active = true;
                user.token = " ";
                db.Entry(user).State = EntityState.Modified;
            }
            try
            {
                db.SaveChanges();
                return BadRequest("OK");
            }
            catch (DbUpdateConcurrencyException)
            {
                
                    throw;
                
            }
        }

        [HttpGet]
        [Route("api/Users/changepswd")]
        [ResponseType(typeof(void))]
        public IHttpActionResult Changepswd(long id, string oldpwd, string newpwd)
        {
            if (oldpwd != newpwd)
            {
                string oldpass= Encrypt.GetSHA256(oldpwd);
                string newpass = Encrypt.GetSHA256(newpwd);
                Usuario user = db.Usuario.Where(a => a.id_usuario == id && a.password == oldpass).FirstOrDefault();
                if (user != null)
                {
                    user.password = newpass;
                    db.Entry(user).State = EntityState.Modified;

                }
                try
                {
                    db.SaveChanges();
                    return NotFound();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            else
            {
                string MensajeError = "El nuevo password no puede ser igual al anterior";
                return BadRequest(MensajeError);
            }
        }


        [Route("api/Users/register")]
        [HttpPost]
        [ResponseType(typeof(Usuario))]
        public IHttpActionResult Register(Usuario usuario)
        {
            string MensajeError = "Error";
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            else
            {
                //CHEQUEA QUE EL MAIL NO ESTA EN USO
                Usuario emailcheck = db.Usuario.Where(a => a.email == usuario.email).FirstOrDefault();
                if (emailcheck != null)
                {
                    // return new Respuesta
                    // { Estado = "Error", Mensaje = "El email ya se encuentra registrado" };
                    MensajeError = "El email ya se encuentra registrado";
                    return BadRequest(MensajeError);
                }
                //CHEQUEA QUE EL NOMBRE DE USUARIO NO ESTE EN USO
                Usuario usercheck = db.Usuario.Where(a => a.nickname == usuario.nickname).FirstOrDefault();
                if (usercheck != null)
                {
                    MensajeError = "El usuario ya se encuentra registrado";
                    return BadRequest(MensajeError);
                }
                //ENCRIPTA CONTRASEÑA
                string pswd = Encrypt.GetSHA256(usuario.password);
                usuario.password = pswd;
                string tkn = Guid.NewGuid().ToString();
                usuario.rol = 1;
                usuario.active = false;
                usuario.token = tkn;
                usuario.user_foto = "/img/profile.png";
                //SI LA DESCRIPCION DE USUARIO ES VACIA CREO UNA CADENA PARA RELLENAR EL CAMPO
                if (usuario.user_descripcion == null)
                {
                    usuario.user_descripcion = "El Usuario: " + usuario.nickname + " no agregó descripción pero su email es: " + usuario.email;
                }
                db.Usuario.Add(usuario);
                      db.SaveChanges();
                //Send Email to User
                EnviarMailVerificador(usuario.email, usuario.token.ToString(), usuario.id_usuario);
            }
            return CreatedAtRoute("DefaultApi", new { id = usuario.id_usuario }, usuario); ;
        }

        private void EnviarMailVerificador(string email, string tkn, long id)
        {
            var UrlVerifica = "/verifica/" + tkn;
           // var UrlSite = "https://localhost:44331/Bundles/#";
            var UrlSite = "https://fullviajesdemo.azurewebsites.net/Bundles/#";
            var link = UrlSite+UrlVerifica;

            var DesdeEmail = new MailAddress("fullviajestest@m3s.com.ar", "FullViajes Registro de Usuarios");
            var HaciaEmail = new MailAddress(email);
            var DesdeEmailPassword = "fullviajesprueba";
            string subject = "Su cuenta el Full Viajes se ha creado satisfactoriamente";

            string body = "<br/><br/>Estamos muy alegres que te hayas registrado en FullViajes. <br/><br/>Su cuenta ha sido creada correctamente pero debe verificar su mail para activar la cuenta" +
                "<br/><br/>Debe hacer click en el siguiente vinculo para poder acceder " +

VS_Project/FullViajes/FullViajes/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using FullViajes.Models;
using System.Security.Cryptography;
using System.Text;

//CLASE PARA ENCRIPTAR EL PASSWORD DEL USUARIO
public class Encrypt
{
    public static string GetSHA256(string str)
    {
        SHA256 sha256 = SHA256Managed.Create();
        ASCIIEncoding encoding = new ASCIIEncoding();
        byte[] stream = null;
        StringBuilder sb = new StringBuilder();
        stream = sha256.ComputeHash(encoding.GetBytes(str));
        for (int i = 0; i < stream.Length; i++) sb.AppendFormat("{0:x2}", stream[i]);
        return sb.ToString();
    }

}


namespace FullViajes.Controllers
{
    public class UsuarioController : Controller
    {
        FullViajesEntities db = new FullViajesEntities();
        public string MessaError { get; private set; }
        //MUESTRA LISTADO GENERAL
        public ActionResult Index()
        {
            if (Session["idUsuario"] != null)
            {
                if (Convert.ToInt32(Session["rol"]) == 0)
                {
                    List<Usuario> listaUsuarios = db.Usuario.ToList();
                    return View(listaUsuarios);
                }
                else
                {
                    return Redirect("~/Users/Privi");
                }
            }
            else
            {
                return Redirect("~/Users");
            }

        }
        //MUESTRA EL DETALLE DE USUARIO        
        public ActionResult Perfil(int id)
        {
            if (id == null)//El resultado es siempre false porque un valor de tipo int nunca es igual a null
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // INGRESA NUEVO USUARIO
        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(Usuario oUser)
        {
            string MensajeError = "Error";
            try
            {
                if (ModelState.IsValid)
                {
                    using (FullViajesEntities db = new FullViajesEntities())
                    {
                        //CHEQUEA QUE EL MAIL NO ESTA EN USO
                        Usuario emailcheck = db.Usuario.Where(a => a.email == oUser.email).FirstOrDefault();
                        if (emailcheck != null)
                        {   
                            ModelState.AddModelError("email", "El email ya se encuentra registrado");
                            return View();
                        }
                        //CHEQUEA QUE EL NOMBRE DE USUARIO NO ESTE EN USO
                        Usuario usercheck = db.Usuario.Where(a => a.nickname == oUser.nickname).FirstOrDefault();
                        if (usercheck != null)
                        {
                            ModelState.AddModelError("nickname", "El usuario " + oUser.nickname + " ya se encuentra registrado");
                            return View();
                        }
                        //ENCRIPTA CONTRASEÑA
                        string pswd = Encrypt.GetSHA256(oUser.password);
                        oUser.password = pswd;
                        //EN CASO DE QUE NO SE HAYA CARGADO FOTO DE PERFIL ASIGNA UNA, POR AHORA ASIGNA DIRECTAMENTE HASTA VER COMO FUNCIONA IMAGE-UPLOAD
                        //if (oUser.user_foto == null)
                        //{
                        oUser.user_foto = "/img/profile.png";
                        //}
                        //ASIGNO ROL 1=USUARIO REGISTRADO
                        oUser.rol = 1;
                        oUser.active = true;
                        oUser.token = "";
                        //SI LA DESCRIPCION DE USUARIO ES VACIA CREO UNA CADENA PARA RELLENAR EL CAMPO
                        if (oUser.user_descripcion == null)
                        {
                            oUser.user_descripcion = "El Usuario: " + oUser.nickname + " no agregó descripción pero su email es: " + oUser.email;
                        }
                        db.Usuario.Add(oUser);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        //MODIFICA DATOS DE USUARIO
        public ActionResult Modificar(int id)
        {
            Usuario usuario = db.Usuario.Find(id);
            return View(usuario);
        }
        [HttpPost]
        public ActionResult Modificar(Usuario oUser)
        {
            try
            {
                Usuario usuario = db.Usuario.Find(oUser.id_usuario);
                //CHEQUEA QUE EL MAIL NO ESTE EN USO SALVO EN EL USUARIO QUE SE ESTA MODIFICANDO
                Usuario emailcheck = db.Usuario.Where(a => a.email == oUser.email && a.id_usuario != oUser.id_usuario).FirstOrDefault();
                if (emailcheck != null)
                {
                    ModelState.AddModelError("email", "El email ya se encuentra registrado");
                    return View();
                }
                //CHEQUEA QUE EL NOMBRE DE USUARIO NO ESTE EN USO SALVO EN EL USUARIO QUE SE ESTA MODIFICANDO
                Usuario usercheck = db.Usuario.Where(a => a.nickname == oUser.nickname && a.id_usuario != oUser.id_usuario).FirstOrDefault();
                if (usercheck != null)
                {
                    ModelState.AddModelError("nickname", "El usuario " + oUser.nickname + " ya se encuentra registrado");
                    return View();
                }
                //ENCRIPTE LOS PASSWORDS CARGADOS EN TEXTO SIMPLE REENCRIPTANDO LO YA CARGADO
                // string pswd = Encrypt.GetSHA256(oUser.password);
                // usuario.password = pswd;
                usuario.nombre = oUser.nombre;
                usuario.apellido = oUser.apellido;
                usuario.nickname = oUser.nickname;
                usuario.email = oUser.email;
                //VUELVO A ASIGNAR LA IMAGEN POR DEFECTO HASTA VER IMAGE-UPLOAD
                usuario.user_foto = "/img/profile.png";
                //CHEQUEA QUE DESCRIPCION NO SE HAYA BORRADO Y SINO MODIFICA POR EL DATO QUE VIENE 
                if (oUser.user_descripcion == null)
                {
                    usuario.user_descripcion = "El Usuario: " + usuario.nickname + " no agregó descripción pero su email es: " + usuario.email;
                }
                else
                {
                    usuario.user_descripcion = oUser.user_descripcion;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        //ELIMINA EL USUARIO
        public ActionResult Eliminar(int id)
        {
            Usuario oUser = db.Usuario.Find(id);
            db.Usuario.Remove(oUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

VS_Project/FullViajes/FullViajes/Views/Shared/_FrontLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="favicon.ico">
    <!--CSS-->
    <link rel="stylesheet" href="~/Content/styles.css">
    <script src="https://kit.fontawesome.com/4eb7c88f62.js" crossorigin="anonymous"></script>
    <!-- Seccion de bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <!--RalewayFont-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;1,300&display=swap" rel="stylesheet">
</head>


<body>


    <main>
        <!-- Sección Navbar -->
        <header class=" header">
            <nav class="navbar navbar-expand-lg navbar-light bg-light" style="color: transparent;">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="~/Home"> <button>Inicio</button> <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <button>Ciudades</button>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Ciudad1</a>
                                <a class="dropdown-item" href="#">Ciudad2</a>
                                <a class="dropdown-item" href="#">Ciudad3</a>
                            </div>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#"> <button>Contactanos </button> <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#"> <button> <i class="fas fa-search"></i> Buscar </button> <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="~/Users"> <button style="width: 185px;">   Login/ ¿Nuevo Usuario?  </button> <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>FullViajes &copy; @DateTime.Now.Year</p>
            </footer>
        </div>

    </main>
</body>

</html>

VS_Project/FullViajes/FullViajes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar bg-info navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FullViajes Backend", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Datos de Sesion", "Index", "Users")</li>
                    <li>@Html.ActionLink("Administrar Usuarios", "Index", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>FullViajes &copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>